### ISSUE TITLE
RSS Viide

### ISSUE THREAD

**Issue by ma22** [ma22/Projekt1#11]
Saidil on töötav RSS viide

**Comment by SilleU** [comment]
<br>

<a href="http://puddlejumper.me/feed/">
<img src="http://puddlejumper.me/wp-content/uploads/2017/11/feed-icon-28x28.png" alt="Subscribe to RSS Feed" /></a>

**Comment by SilleU** [comment]
```
<br>

<a href="http://puddlejumper.me/feed/">
<img src="http://puddlejumper.me/wp-content/uploads/2017/11/feed-icon-28x28.png" alt="Subscribe to RSS Feed" /></a>
```
