### ISSUE TITLE
Kommentaarid; DISQUS

### ISSUE THREAD

**Issue by ma22** [ma22/Projekt1#4]
Saidil saab lisada kommentaare postitustele või e-poe puhul toodetele, soovitavalt eraldi lisatud DISQUS vms, mitte sisseehitatud moodul.

**Comment by SilleU** [comment]
Disqus lehel tegin konto.
Valisin "I want to install Disqus on my site".
Registreerisin lehe.

Seejärel wordpressis järgisin Disqus'i õpetust:
In the left panel of your WordPress admin, select Plugins > Add New
Search for "Disqus" and find the plugin provided by "Disqus".
Select Install Now > Activate Plugin
Proceed with the onscreen install instructions.
Log into your Disqus account, then choose the forum shortname you would like to install (https-puddlejumper-me).

**Comment by ma22** [comment]
Disqusi lisamine tõi kaasa metaandmed postitustele, millest tahtsime lahti saada. Selleks avasime content-single.php ning arvasime postitustest välja metaandmed, välja arvatud siis filmide ja muusika puhul 'kestvus'

//the_meta();
		if(get_post_custom_values( 'kestvus' )[0]){
			echo("Kestvus: ".get_post_custom_values( 'kestvus' )[0]);
		}
